version: "3"

services:
  db:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Aa12345678!
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./mydatavolume:/var/lib/my
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always
  backendserver:
    build: ./inventorybacked
    ports:
      - "3000:3000"
    links:
      - "db"
    depends_on:
      - "db"
    restart: always
  frontend:
    build: ./inventSystem/
    links:
      - "backendserver"
    depends_on:
      - "backendserver"
    ports:
      - "4200:4200"
